In [13]:
import numpy as np
import pandas as pd
df = pd.read_csv('odb.csv')
df.head()

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,0,SR Tendulkar (INDIA),1989-2012,463,452,41,18426,200*,44.83,21368,86.23,49,96,20,2016,195
1,1,V Kohli (INDIA),2008-2021,254,245,39,12169,183,59.07,13061,93.17,43,62,13,1140,125
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,39,13704,164,42.03,17046,80.39,30,82,20,1231,162
3,3,RG Sharma (INDIA),2007-2021,227,220,32,9205,264,48.96,10354,88.90,29,43,13,832,244
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,18,13430,189,32.36,14725,91.20,28,68,34,1500,270

In [14]:
df.drop(columns=['4s','6s','0','HS','NO','BF'])

,Unnamed: 0,Player,Span,Mat,Inns,Runs,Ave,SR,100,50
0,0,SR Tendulkar (INDIA),1989-2012,463,452,18426,44.83,86.23,49,96
1,1,V Kohli (INDIA),2008-2021,254,245,12169,59.07,93.17,43,62
2,2,RT Ponting (AUS/ICC),1995-2012,375,365,13704,42.03,80.39,30,82
3,3,RG Sharma (INDIA),2007-2021,227,220,9205,48.96,88.90,29,43
4,4,ST Jayasuriya (Asia/SL),1989-2011,445,433,13430,32.36,91.20,28,68
...,...,...,...,...,...,...,...,...,...,...
114,114,SK Raina (INDIA),2005-2018,226,194,5615,35.31,93.50,5,36
115,115,H Masakadza (ZIM),2001-2019,209,208,5658,27.73,73.21,5,34
116,116,RB Richardson (WI),1983-1996,224,217,6248,33.41,63.74,5,44
117,117,BB McCullum (NZ),2002-2016,260,228,6083,30.41,96.37,5,32
118,118,Saleem Malik (PAK),1982-1999,283,256,7170,32.88,76.41,5,47