In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
path="/content/drive/MyDrive/ML Lab/Exp02/Salary.csv"
df=pd.read_csv(path)

In [ ]:
df.head(16)

    YEARS  SALARY
0       0   25000
1       1   32000
2       2   38000
3       3   44000
4       4   50000
5       5   56000
6       6   62000
7       7   65000
8       8   70000
9       9   74000
10     10   80000
11     11   91000
12     12   95000
13     13  100000
14     14  108000
15     15  150000

PreProcessing

In [ ]:
#1.Filter(Not Required Does Not Have Irrelevent Features)
#2.Handling Non-Numeric Data(Not Required Because Data Set HAs Only Numeric Data)
#3.Handling Missing Data(#No Missing Data)

#4.Normalization Or Scaling(Required)
col=['SALARY']
df[col]=(df[col]-df[col].min())/(df[col].max()-df[col].min())
df.head(16)

    YEARS  SALARY
0       0   0.000
1       1   0.056
2       2   0.104
3       3   0.152
4       4   0.200
5       5   0.248
6       6   0.296
7       7   0.320
8       8   0.360
9       9   0.392
10     10   0.440
11     11   0.528
12     12   0.560
13     13   0.600
14     14   0.664
15     15   1.000

**Simple** **Linear** **Regression**

Split Data

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(
    df['YEARS'],df['SALARY'],test_size=0.2,random_state=42
)

Train Model

In [27]:
model=LinearRegression()
model.fit(X_train.values.reshape(-1, 1),Y_train)

LinearRegression()

Prediction

In [33]:
years = [[5]]
predicted_salary = model.predict(years)
print("Normalized Salary:", predicted_salary[0])

original_salary = predicted_salary*(df['SALARY'].max() - df['SALARY'].min()) + df['SALARY'].min()
print("Original Salary:",original_salary)

Normalized Salary: 0.22585559566787006
Original Salary: [0.2258556]

In [39]:
y_pred = model.predict(X_test.values.reshape(-1, 1))

print("R² Score:", r2_score(Y_test, y_pred))
print("MSE:", mean_squared_error(Y_test, y_pred))

R² Score: 0.9602463501406381
MSE: 0.002696092533461922